import os

translation_dict = {
  "af": "Hello Wêreld!",
  "sq": "Përshendetje Botë!",
  "am": "ሰላም ልዑል!",
  "ar": "مرحبا بالعالم!",
  "hy": "Բարեւ աշխարհ!",
  "eu": "Kaixo Mundua!",
  "be": "Прывітанне Сусвет!",
  "bn": "ওহে বিশ্ব!",
  "bg": "Здравей свят!",
  "ca": "Hola món!",
  "ny": "Moni Dziko Lapansi!",
  "zh": "你好世界！",
  "hr": "Pozdrav svijete!",
  "cs": "Ahoj světe!",
  "da": "Hej Verden!",
  "nl": "Hallo Wereld!",
  "en": "Hello World!",
  "et": "Tere maailm!",
  "fi": "Hei maailma!",
  "fr": "Bonjour monde!",
  "fy": "Hallo wrâld!",
  "ka": "გამარჯობა მსოფლიო!",
  "de": "Hallo Welt!",
  "el": "Γειά σου Κόσμε!",
  "ha": "Sannu Duniya!",
  "he": "שלום עולם!",
  "hi": "नमस्ते दुनिया!",
  "hu": "Helló Világ!",
  "is": "Halló heimur!",
  "ig": "Ndewo Ụwa!",
  "id": "Halo Dunia!",
  "it": "Ciao mondo!",
  "ja": "こんにちは世界！",
  "kk": "Сәлем Әлем!",
  "km": "សួស្តី​ពិភពលោក!",
  "ko": "안녕하세요 월드입니다!",
  "jy": "Салам дүйнө!",
  "lo": "ສະ​ບາຍ​ດີ​ຊາວ​ໂລກ!",
  "lv": "Sveika pasaule!",
  "lt": "Labas pasauli!",
  "lb": "Moien Welt!",
  "mk": "Здраво свету!",
  "ml": "Hai dunia!",
  "ms": "ഹലോ വേൾഡ്!",
  "mn": "Сайн уу дэлхий!",
  "my": "မင်္ဂလာပါကမ္ဘာလောက!",
  "ne": "नमस्कार संसार!",
  "no": "Hei Verden!",
  "ps": "سلام نړی!",
  "fa": "سلام دنیا!",
  "pl": "Witaj świecie!",
  "pt": "Olá Mundo!",
  "pa": "ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ ਦੁਨਿਆ!",
  "ro": "Salut Lume!",
  "ru": "Привет мир!",
  "gd": "Hàlo a Shaoghail!",
  "sr": "Здраво Свете!",
  "st": "Lefatše Lumela!",
  "si": "හෙලෝ වර්ල්ඩ්!",
  "sl": "Pozdravljen svet!",
  "es": "¡Hola Mundo!",
  "su": "Halo Dunya!",
  "sw": "Salamu Dunia!",
  "sv": "Hej världen!",
  "tg": "Салом Ҷаҳон!",
  "th": "สวัสดีชาวโลก!",
  "tr": "Selam Dünya!",
  "uk": "Привіт Світ!",
  "uz": "Salom Dunyo!",
  "vi": "Chào thế giới!",
  "cy": "Helo Byd!",
  "xh": "Molo Lizwe!",
  "ji": "העלא וועלט!",
  "yo": "Mo ki O Ile Aiye!",
  "zu": "Sawubona Mhlaba!"
}


system_language = os.environ['LANG'][:2]
print(translation_dict[system_language[:2]])
